
export const LegalErrors = {
    LEGAL_COMPETENCE_ERROR: "LEGAL_COMPETENCE_ERROR",
    QUORUM_ERROR: "QUORUM_ERROR",
    MANDATE_CONFLICT_ERROR: "MANDATE_CONFLICT_ERROR",
    STATUTE_VIOLATION_ERROR: "STATUTE_VIOLATION_ERROR",
    IMMUTABILITY_VIOLATION_ERROR: "IMMUTABILITY_VIOLATION_ERROR",
    ASSOCIATION_NOT_FOUND: "ASSOCIATION_NOT_FOUND",
    INVALID_AMOUNT: "INVALID_AMOUNT",
    LEGAL_DUPLICATE_ACT_ERROR: "LEGAL_DUPLICATE_ACT_ERROR",
    MANDATE_ALREADY_ACTIVE: "MANDATE_ALREADY_ACTIVE",
    ASSEMBLY_ALREADY_HELD: "ASSEMBLY_ALREADY_HELD",
    STATUTE_NOT_CONSOLIDATED: "STATUTE_NOT_CONSOLIDATED",
    ILLEGAL_STATE_TRANSITION: "ILLEGAL_STATE_TRANSITION"
} as const;




export type LegalErrorCode = typeof LegalErrors[keyof typeof LegalErrors];

export class DomainError extends Error {
    constructor(public code: LegalErrorCode, message: string) {
        super(message);
        this.name = "DomainError";
    }
}
